# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import PyQt5.sip
import win32api
import win32con
import win32gui

class test_form(QtWidgets.QWidget):
    def __init__(self, main):
        QtWidgets.QWidget.__init__(self)
        
        self.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        self.setStyleSheet('QMainWindow {background-color: #FFFFFF; color: #FFFFFF;}')
        self.resize(win32api.GetSystemMetrics(0), win32api.GetSystemMetrics(1))

        # hwnd = int(self.winId())
        # exStyle = win32con.WS_EX_COMPOSITED | win32con.WS_EX_LAYERED | win32con.WS_EX_NOACTIVATE | win32con.WS_EX_TOPMOST | win32con.WS_EX_TRANSPARENT
        # win32gui.SetWindowLong(hwnd, win32con.GWL_EXSTYLE, exStyle)
        # win32gui.SetLayeredWindowAttributes(hwnd, 0x00ffffff, 255, win32con.LWA_COLORKEY | win32con.LWA_ALPHA)
        # win32gui.SetWindowPos(hwnd, win32con.HWND_TOPMOST, 0, 0, 0, 0,
        #     win32con.SWP_NOACTIVATE | win32con.SWP_NOMOVE | win32con.SWP_NOSIZE | win32con.SWP_SHOWWINDOW)
        QtCore.QMetaObject.connectSlotsByName(main)

